# Generated by Django 4.1.7 on 2023-02-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_alter_ordermodel_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
    ]
