# Generated by Django 4.1.7 on 2023-02-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_ordermodel_is_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='pay_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='gmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
